[book]
title = "TTModding - Documentation"
authors = ["Ac_K"]
description = "The home of TT Games LEGO video game modding — Everything you need, all in one place."

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
no-section-label = true
git-repository-url = "https://github.com/AcK77/TTModding-Docs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/AcK77/TTModding-Docs/edit/main/{path}"
cname = "ttmodding.com"
theme = "theme"

[output.html.fold]
enable = true
level = 0

[preprocessor.alerts]

[preprocessor.embedify]
footer.enable = true
footer.message = "Copyright © 2025 • Created with ❤️ by TTModding community."
scroll-to-top.enable = true
